services:
  - type: web
    name: crispor-scraping
    env: python
    buildCommand: docker build -t app .
    startCommand: docker run -p $PORT:$PORT app
    envVars:
      - key: PYTHON_VERSION
        value: 3.9