services:
  - type: web
    name: crispor-scraping
    env: python
    buildCommand: |
      #!/usr/bin/env bash
      # Install Chrome & Chromedriver
      wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add -
      echo "deb http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google.list
      apt-get update -y
      apt-get install -y google-chrome-stable chromium-driver
      # Install Python dependencies
      pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.18
      - key: PORT
        value: 10000
      - key: PYTHONUNBUFFERED
        value: "true"
      - key: CHROME_BIN
        value: /usr/bin/google-chrome
      - key: CHROMEDRIVER_PATH
        value: /usr/bin/chromedriver
    healthCheckPath: /
    autoDeploy: true
    buildFilter:
      paths:
        - requirements.txt
        - "**/*.py"
        - templates/**
        - static/**
    disk:
      name: tmp
      mountPath: /tmp
      sizeGB: 1